# Generated by Django 3.1.1 on 2020-09-14 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginate_by', models.PositiveSmallIntegerField(default=10, help_text='0 means no pagination', verbose_name='Number of items per page')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benutzereinstellungen',
                'verbose_name_plural': 'Benutzereinstellungen',
            },
        ),
    ]
