# Generated by Django 3.1.1 on 2020-09-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='paginate_by',
            field=models.PositiveSmallIntegerField(default=10, help_text='0 bedeutet keine Paginierung', verbose_name='Anzahl Einträge pro Seite'),
        ),
    ]
