# Generated by Django 3.1.7 on 2021-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0002_auto_20200914_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='paginate_by',
            field=models.PositiveSmallIntegerField(default=12, help_text='0 bedeutet keine Paginierung', verbose_name='Anzahl Einträge pro Seite'),
        ),
    ]
