# Generated by Django 5.1.5 on 2025-04-18 10:32
from django.conf import settings
from django.contrib import auth
from django.db import migrations


User = auth.get_user_model()


def propagate_user(apps, schema_editor):
    """
    Propagate the user from the document to the user settings.
    """
    Document = apps.get_model('documents', 'Document')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    cwiegand, _created = User.objects.get_or_create(username='cwiegand')

    for document in Document.objects.all():
        document.user = cwiegand
        document.save()


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0003_document_user'),
    ]

    operations = [
        migrations.RunPython(propagate_user)
    ]
